application: lcdance2011
version: 1
runtime: python
api_version: 1

handlers:

- url: /admin.*
  script: admin.py
  login: admin

- url: /.*
  script: main.py

- url: /favicon.ico
  static_dir: static/favicon.ico

- url: /stylesheets
  static_dir: static/stylesheets
