application: lcdance2011
version: 1
runtime: python
api_version: 1

builtins:
- datastore_admin: on

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /stylesheets/jquery
  static_dir: static/jquery/css/ui-lightness
  
- url: /js/jquery
  static_dir: static/jquery/js

- url: /stylesheets
  static_dir: static/stylesheets

- url: /user_images
  static_dir: static/user_images

- url: /js
  static_dir: static/js

- url: /admin.*|/tasks.*
  script: main.py
  login: admin

- url: /privacy|/contact
  script: main.py

- url: /.+
  script: main.py
  login: required
  
- url: /
  script: main.py