application: lcdance2011
version: 1
runtime: python
api_version: 1

inbound_services:
- mail

handlers:


- url: /_ah/mail/c@.*lcdance2011\.appspotmail.com
  script: email_c.py
  login: admin

- url: /_ah/mail/.+
  script: email_catchall.py
  login: admin

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /stylesheets
  static_dir: static/stylesheets

- url: /admin.*
  script: admin.py
  login: admin

- url: /.+
  script: main.py
  login: required

- url: /
  script: welcome.py
