application: lcdance2011
version: 1
runtime: python
api_version: 1

handlers:
- url: /.*
  script: main.py

- url: /stylesheets
  static_dir: static/stylesheets

- url: /favicon.ico
  static_dir: static/favicon.ico
